### ISSUE TITLE
No tiling after installation/activation

### ISSUE THREAD

**Issue by atomtm** [kwin-scripts/kwin-tiling#194]
So in Debian 10 , I have followed exactly the installation instructions, but after activating the script there is no tiling at all , i.e. behaves as it did before. 
Is there any place I can check for logs and troubleshoot this issue ?
**Edit:**
So after `kwin_x11 --replace` I got : `file:///home/atomtm/.local/share/kwin/scripts/kwin-script-tiling/contents/code/tile.js:493: TypeError: Cannot read property 'length' of undefined
`

**Comment by esjeon** [comment]
Hi, I tried to help this guy in a KDE chat room, but I think this is a code-level issue.

Basically, [the Tile constructor](https://github.com/kwin-scripts/kwin-tiling/blob/daf5745614a415e2419d66b299470f45a3632224/contents/code/tile.js#L27) failed in the middle, with an error saying `TypeError: Property 'from' of object function() { [code] } is not a function in Tile`. I'm pretty sure this is referring to `Array.from`, which is, AFAIK, ECMA 6. It's likely that this function doesn't exist in the old KWin provided by Debian 10, tho not fully confirmed.

I hope this information helps in resolving the issue.

**Comment by telebiker** [comment]
BTW, I used Debian 10 couple of days ago and was able to set up tiling extension without any issues. Unfortunately, this system is not with me right now.

**Comment by ivohulsman** [comment]
I am having the exact same problem on al my Debian 10 boxes. Works fine in an Arch VM.

**Comment by faho** [comment]
Please try a5d94c3.

**Comment by xtarke** [comment]
> Please try [a5d94c3](https://github.com/kwin-scripts/kwin-tiling/commit/a5d94c3eee1ae9af9cb2f3e3e56cf66ce36687c6).

Working in Debian 10.

**Comment by Braincoke** [comment]
> Please try [a5d94c3](https://github.com/kwin-scripts/kwin-tiling/commit/a5d94c3eee1ae9af9cb2f3e3e56cf66ce36687c6).

I just discovered this script. It didn't work on Ubuntu 18.04 after installation but with this branch it runs fine.

**Comment by faho** [comment]
Yeah, it turns out I forgot to merge the fix. Should be working now in master.
